name: CI
on:
  pull_request:
  push:
jobs:
  assemble:
    name: Build and Test Assembly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.${{ matrix.jdk }}"
    - name: Build
      shell: bash
      run: sbt -v -Dfile.encoding=UTF-8 assembly
    - name: Test
      shell: bash
      run: target/scala-2.13/exist-xqts-runner-assembly-1.1.0-SNAPSHOT.jar --xqts-version HEAD --test-set fn-current-date
